version: "3"

services:
  etcd01:
    container_name: etcd01.gsxhnd.xyz
    image: quay.io/coreos/etcd:v3.4.0
    restart: always
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - TZ=CST-8
      - LANG=zh_CN.UTF-8
    command: /usr/local/bin/etcd
      -name etcd01
      -data-dir /etcd-data
      -advertise-client-urls http://etcd01.gsxhnd.xyz:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://etcd01.gsxhnd.xyz:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token docker-etcd
      -initial-cluster etcd01=http://etcd01.gsxhnd.xyz:2380
      --initial-cluster etcd01=http://etcd01.gsxhnd.xyz:2380
      -initial-cluster-state new
    volumes:
      - ./data:/etcd-data
      # - "/data/config/etcd/ca-certificates/:/etc/ssl/certs"
