apiVersion: v1
kind: Pod
metadata:
  name: grafana-ui
  namespace: devops
  labels:
    app: web
spec:
  containers:
    - name: grafana-ui
      image: grafana/grafana:9.3.6-ubuntu
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      env:
        - name: GF_FEATURE_TOGGLES_ENABLE
          value: "newNavigation"
  restartPolicy: Always
