apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deploy
  namespace: devops
  labels:
    app: loki-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki-container
          image: grafana/loki:2.7.4-amd64
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3100
          args: ["-config.file=/etc/loki/local-config.yaml"]
      restartPolicy: Always
