version: "3"

services:
  qbittorrent:
    container_name: qbittorrent
    image: hotio/qbittorrent:release-4.4.0
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    # volumes:
    #   - /<host_folder_config>:/config