version: "3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer:1.23.2
    restart: always
    privileged: false
    ports:
      - 9000:9000
    environment:
      TIME_ZONE: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
