version: '2'

services:
  registry:
    container_name: registry
    restart: always
    image: registry:2.7.1
    ports:
      - 5000:5000
    volumes:
      - ./data/:/var/lib/registry
      - ./data/auth:/auth
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
