FROM ubuntu:22.10

RUN apt update && apt install -y curl zsh git
RUN git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
RUN cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
RUN chsh -s $(which zsh)
RUN apt install build-essential clang flex bison g++ gawk gcc-multilib gettext \
    libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
    file wget