server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki-svc.devops:3100/loki/api/v1/push
scrape_configs:
  - job_name: kubernetes-pods
    kubernetes_sd_configs:
      - role: pod
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            component: component
            timestamp: timestamp
      - timestamp:
          format: RFC3339Nano
          source: timestamp
      - labels:
          level:
          component:
    relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_pod_container_name]
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: service_name
      - source_labels: [__meta_kubernetes_pod_node_name]
        action: replace
        target_label: host
      - source_labels:
        - __meta_kubernetes_pod_label_app
        target_label: __service__
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - source_labels: ["__meta_kubernetes_pod_container_name"]
        target_label: __path__
        replacement: /var/log/pods/*$1/*.log
