version: "3"

networks:
  drone:
    external: false

services:
  drone:
    image: drone/drone:2.14.0 
    container_name: drone
    environment:
      - DRONE_GITEA_SERVER=[]
      - DRONE_GITEA_CLIENT_ID=[]
      - DRONE_GITEA_CLIENT_SECRET=[]
      - DRONE_RPC_SECRET=[]
      - DRONE_SERVER_HOST=[]
      - DRONE_SERVER_PROTO=https
    restart: always
    networks:
      - drone
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:80"