FROM alpine:3.15

LABEL maintainer="gsxhnd@gmail.com"

WORKDIR /app
COPY frps /app/
COPY conf/frps.ini /app/conf/FROM alpine:3.15

LABEL maintainer="gsxhnd@gmail.com"

COPY frps /app/FROM alpine:3.15

LABEL maintainer="gsxhnd@gmail.com"

COPY frps /app/