version: "3.4"

networks:
  default:
    name: devops

services:
  influxdb_v2:
    container_name: influxdb
    image: influxdb:2.7.11
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=root@123
      - DOCKER_INFLUXDB_INIT_ORG=test_g
      - DOCKER_INFLUXDB_INIT_BUCKET=test_bucket
