version: "3"
services:
  jenkins:
    restart: always
    image: jenkins/jenkins:2.204.1-alpine
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./data/jenkins:/var/jenkins_home
