apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-role
rules:
  - apiGroups: [""]
    resources:
      ["nodes", "nodes/proxy", "pods", "services", "pods/log", "endpoints"]
    verbs: ["get", "watch", "list"]
