apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: log-role-bind
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: devops
roleRef:
  kind: ClusterRole
  name: promtail-role
  apiGroup: rbac.authorization.k8s.io
