version: "2"

networks:
  dipole.tech:
    external:
      name: net_dipole

services:
  es01:
    container_name: es01.dipole.tech
    image: elasticsearch:7.3.1
    environment:
      - node.name=es01.dipole.tech
      # - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01.dipole.tech
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
        - ./node1/data:/usr/share/elasticsearch/data:rw
        - ./node1/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - ./node1/logs:/user/share/elasticsearch/logs:rw    
    networks: 
      dipole.tech:
        aliases:
          - es01.dipole.tech
  # es02:
  #   container_name: es02.dipole.tech
  #   image: elasticsearch:7.3.1
  #   environment:
  #     - cluster.name=docker-cluster
  #     - cluster.initial_master_nodes=["node-1"]
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   ports:
  #     - "9200:9200"
  #   networks: 
  #     dipole.tech:
  #       aliases:
  #         - es02.depole.tech
  kibana:
    container_name: kibana.dipole.tech
    image: kibana:7.3.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es01.dipole.tech:9200
    ports:
      - "5601:5601"
    networks: 
      dipole.tech:
        aliases:
          - kibana.dipole.tech