version: '2'

services:
  nginx:
    container_name: nginx-proxy
    restart: always
    image: nginx:1.17.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./www:/var/www
      - ./ssl:/etc/nginx/ssl
