version: "3"

services:
  frps:
    container_name: frps
    image: gsxhnd/frps:0.36.1
    restart: always
    ports:
      - 7000:7000
      - 7500:7500
      - 8000:8000
    command: "./frps -c /frps/conf/frps.ini"
    environment:
      TIME_ZONE: Asia/Shanghai
    volumes:
      - ./conf:/frps/conf
