version: "3"

services:
  jupyter:
    container_name: jupyter
    image: jupyter/scipy-notebook:latest
    restart: always
    privileged: false
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
