server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki-svc.devops:3100/loki/api/v1/push
scrape_configs:
- job_name: kubernetes-pods
  pipeline_stages:
    - docker: {}
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_pod_node_name
    target_label: __host__
  # Add pod labels as prometheus labels
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
    
  - source_labels: [__meta_kubernetes_namespace]
    target_label: namespace
  - source_labels: [__meta_kubernetes_pod_name]
    target_label: pod
  # Set the file path to read logs from
  - source_labels:
    - __meta_kubernetes_pod_uid
    - __meta_kubernetes_pod_container_name
    separator: /
    target_label: __path__
    replacement: /var/log/pods/*$1/*.log