version: "3"

services:
  grafana:
    image: grafana/grafana:main
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=newNavigation