version: "3"

networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:1.17.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - RUN_MODE=prod
      - DOMAIN=[DOMAIN]
      - DISABLE_SSH=true
      - HTTP_PORT=5000
      - LFS_START_SERVER=true
      - DB_TYPE=sqlite3
      - DISABLE_REGISTRATION=true
    restart: always
    networks:
      - gitea
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5000:5000"