version: "3"

networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:1.22.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - RUN_MODE=prod
      - DOMAIN=[DOMAIN]
      - DISABLE_SSH=false
      - HTTP_PORT=3100
      - LFS_START_SERVER=true
      - DB_TYPE=sqlite3
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=true
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3100:3100"
      - "222:22"
