version: "3"

services:
  mongodb-01:
    container_name: mongodb-01
    image: mongo:4.2.0
    restart: always
    ports:
      - "27017:27017"
    command: "mongod --config /etc/mongo.yaml "
    volumes:
      - "./mongodata/db:/data/db"
      - "./mongodata/mongo.yaml:/etc/mongo.yaml"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
