version: "3"

services:
  mongodb01:
    container_name: mongodb01
    image: mongo:4.2.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodata/db:/data/db
      # - "/data/mongodata/mongo.conf:/etc/mongo.conf"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
