version: "3"

services:
  redis:
    image: redis:6.2.5-alpine3.14
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: --appendonly yes
    volumes:
      - ./data:/data
      # - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
