version: '3'

services:
  redis:
    image: redis:alpine3.10
    container_name: redis01
    restart: always
    ports:
      - 6379:6379
    command: --appendonly yes
    volumes:
      - ./data:/data
      # - ./conf/redis.conf:/usr/local/etc/redis/redis.conf