name: BuildClionDevImage

on:
  push:
    paths:
      - "container/clion.cpp.dockerfile"

jobs:
  Build:
    name: BuildDevImage
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: docker build -f container/clion.cpp.dockerfile -t gsxhnd/clion:cpp.v0.0.1 .
      - name: Push Image
        run: docker push gsxhnd/clion:cpp.v0.0.1
