name: BuildClionDevImage

on:
  push:
    paths:
      - "container/clion.cpp.dockerfile"
      - ".github/workflows/clion.container.yml"

jobs:
  Build:
    name: BuildDevImage
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          platforms: linux/amd64,linux/arm64
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./container/clion.cpp.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: gsxhnd/clion:cpp.latest
