name: BuildDevImage

on:
  push:
    paths:
      - 'container/dev.base.dockerfile'
      - 'container/dev.cli.dockerfile'
      - 'container/dev.full.dockerfile'

jobs:
  Build:
    name: BuildDevImage
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image And Push
        run: make