name: BaseDevContainer

on:
  push:
    paths:
      - 'container/base.dev.dockerfile'
      - 'container/dev.dockerfile'
      - 'container/deploy.dockerfile'

jobs:
  Build:
    name: BuildDevConatiner
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Base Dev Image
        run: |
          docker build -f container/base.dev.dockerfile -t gsxhnd/dev-container:base .
          echo "gsxhnd/dev-container:base" >> ./scripts/images.txt
      - name: Build Dev Image
        run: |
          docker build -f container/dev.dockerfile -t gsxhnd/dev-container:all .
          echo "gsxhnd/dev-container:all" >> ./scripts/images.txt
      - name: Build Deploy Image
        run: |
          docker build -f container/deploy.dockerfile -t gsxhnd/dev-container:deploy .
          echo "gsxhnd/dev-container:deploy" >> ./scripts/images.txt
      - name: Push Image
        run: |
          chmod +x ./scripts/push_images.sh
          ./scripts/push_images.sh
