name: BuildImage

on:
  push:
    paths:
      - 'Dockerfile*'

jobs:
  BuildImage:
    name: BuildImage
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build Base Image
        run: "docker build -f Dockerfile.base -t ghcr.io/gsxhnd/openwrt:ubuntu22.10-zsh ."

      - run: docker images

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/gsxhnd/openwrt:ubuntu22.10-zsh