name: BuildImage

on:
  push:
    paths:
      - 'Dockerfile*'

jobs:
  BuildImage:
    name: BuildImage
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Build Base Image
        run: "docker build -f Dockerfile.base -t gsxhnd/openwrt:ubuntu22.10-zsh ."

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: docker push gsxhnd/openwrt:ubuntu22.10-zsh