name: LLVMDevContainer

on:
  push:
    paths:
      - 'llvm.dev.dockerfile'
jobs:
  Build:
    name: BuildLLVMDevConatiner
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Base Image
        run: "docker build -f llvm.dev.dockerfile -t gsxhnd/dev-container:llvm15-ubuntu ."
      - name: Push Base Image
        run: docker push gsxhnd/openwrt:22.03-ubuntu22.10-base
