name: BuildOpenWrtDevContainer

on:
  push:
    paths:
      - 'container/openwrt.base.dockerfile'
jobs:
  Build:
    name: BuildOpenWrtBaseImage
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Openwrt Base Image
        run: "docker build -f container/openwrt.base.dockerfile -t gsxhnd/openwrt:22.03-ubuntu22.10-base ."
      - name: Push Base Image
        run: docker push gsxhnd/openwrt:22.03-ubuntu22.10-base
